### ISSUE TITLE
notifyFulfillment does not get called with IAP 2.0 implementation

### ISSUE THREAD

**Issue by Kmess** [soomla/android-store-amazon#2]
Seeing an issue with the latest implementation of the SOOMLA plugin regarding the new Amazon IAP 2.0.

After making an IAP, notifyFulfillment does not get called - this is a requirement for app submissions to the Amazon app store.

For additional notes - https://developer.amazon.com/public/apis/earn/in-app-purchasing/docs-v2/migrate-iapv1-apps-to-iapv2?ref_=pe_679090_102923190

**Comment by sluzky** [comment]
Hey @Kmess,

We have made the necessary fixes to the plugin, can you test with the following [AndroidStoreAmazon.jar](http://www.adrive.com/public/sBWdUD/AndroidStoreAmazon.jar), and let us know if it works for you?

**Comment by Kmess** [comment]
Hi Simon, I noticed that the onPurchaseResponse does not have notifyFulfillment in all of the response paths (ie INVALID_SKU, ALREADY_PURCHASED, Default). I'm assuming that even if the purchase fails a notifyFulfillment(response.getReceipt().getReceiptId(), FulfillmentResult.UNAVAILABLE) will need to occur.

**Comment by sluzky** [comment]
@Kmess you are correct not all paths get to `notifyFulfillment`.
I agree that perhaps `INVALID_SKU` should send `notifyFulfillment` with `FulfillmentResult.UNAVAILABLE`, but could you explain why would `ALREADY_PURCHASED` should do the same? if it's already purchased it should already be fulfilled as well.
Same goes to Default, why would a general failure make the product unavailable?

This [article](https://developer.amazon.com/public/apis/earn/in-app-purchasing/docs-v2/migrate-iapv1-apps-to-iapv2) specifically notes: 
> If the fulfillment can not occur because the item was for a previous game state or the game does not support that item, then call notifyFulfillment() for the receiptId with the status UNAVAILABLE. **Do not send this status if you encounter an interim error during receipt processing**.

**Comment by sluzky** [comment]
@Kmess from my tests and according to Amazon's SDK samples, when getting `INVALID_SKU` you cannot `notifyFulfillment` with `FulfillmentResult.UNAVAILABLE`, since you do not have a receipt ID at that point.

I added the `notifyFulfillment` with `FulfillmentResult.UNAVAILABLE`, according to Amazon's samples in the restore transactions part, where we can check if the SKU is no longer available and send the notification accordingly. See the last commit, I have sent you the JAR for testing.

**Comment by Kmess** [comment]
Great, tesing passed and it is compliant with Amazon's approval process.

Thanks @sluzky!
